### ISSUE TITLE
起動時にブラウザで UI を開きたい

### ISSUE THREAD

**Issue by plonk** [plonk/peercast-yt#76]
これが GUI なので。VPS で起動した時はブラウザを立ち上げたくない。DISPLAY 環境変数が用意されている時だけとか？

MinGW では無条件に開いていいと思う。

**Comment by plonk** [comment]
DISPLAY 環境変数が無い時は xdg-open が失敗するようだから、場合分けはしなくてよさそう。

**Comment by plonk** [comment]
マスターブランチで実装した。

**Comment by plonk** [comment]
URLを開くのは PeercastInstance (さらに Sys に委譲)じゃなくて PeercastApplication の仕事なんじゃないかと思った。

**Comment by plonk** [comment]
Build Verification Test がコケてた。何らかのテキストブラウザを起動として、何かのテキストブラウザが立ち上がったらしい。

```
00-smoke: /usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found
ok
01-int-kills: w3m: Can't load http://localhost:7144/html/en/index.html.
xdg-open: no method available for opening 'http://localhost:7144/html/en/index.html'
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found
│v0.1218 YT22
│
│InformationBandwidth
│ViewConnections
│≪ ↑ ↓ Viewing <Information - PeerCast on   127.0.0.1:7144>ain>': unhandled exception
	from 01-int-kills.rb:15:in `loop'
	from 01-int-kills.rb:15:in `<main>'
failed
```

**Comment by plonk** [comment]
DISPLAY環境変数がある時だけブラウザを立ち上げるようにした。 https://github.com/plonk/peercast-yt/commit/161a620bae1f1c05a1617fbde64f39d1f3c057f4

（ついでにshellescapeしている範囲がおかしかったのも直した。)
